# kind: Service
# apiVersion: v1
# metadata:
#   name: nginx-ingress
#   namespace: nginx-ingress
#   labels:
#     app.kubernetes.io/name: nginx-ingress
#     app.kubernetes.io/part-of: nginx-ingress
# spec:
#   externalTrafficPolicy: Local
#   type: LoadBalancer
#   selector:
#     app.kubernetes.io/name: nginx-ingress
#     app.kubernetes.io/part-of: nginx-ingress
#   ports:
#     - name: http
#       port: 80
#       targetPort: http
#     - name: https
#       port: 443
#       targetPort: https